### no locked traits

POST http://localhost:10000/randomize-traits HTTP/1.1
Content-Type: application/json

{
 "lockedTraits": [],
 "classes": 10,
 "subclasses": [3, 3, 4, 5, 2, 6, 3, 3, 4, 5],
 "species": 9,
 "origins": 12,
 "alignments": 9
}


### locked trait

POST http://localhost:10000/randomize-traits HTTP/1.1
Content-Type: application/json

{
 "lockedTraits": ["origins"],
 "classes": 10,
 "subclasses": [3, 3, 4, 5, 2, 6, 3, 3, 4, 5],
 "species": 9,
 "origins": 12,
 "alignments": 9
}
